Create twitter personal page
tokachev/twitter-demo-frontend pull request #2
Opened 2018-06-16 20:38 UTC by tokachev

2018-06-18 07:45 UTC, imevro requested changes

2018-06-18 07:45 UTC, evgenyrodionov commented on src/Header.js
> +import home from "./svg/icon-home.svg";
1) как дальше в коде понять что такое home
2) зачем ты кладёшь в директорию svg? завтра сменим на webp, будешь менять название директории?

2018-06-18 07:45 UTC, evgenyrodionov commented on src/Header.js
> +const Header = styled.div`
htmlreference.io/element/header

2018-06-18 07:45 UTC, evgenyrodionov commented on src/Main/ProfileStat.js
> +            <StatTab state="active">
https://reacttraining.com/react-router/web/api/NavLink

2018-06-18 07:45 UTC, evgenyrodionov commented on src/Main/TweetList/Menu.js
> +    <MenuLink to="/EveryInteract">Tweets & replies</MenuLink>
почему у тебя все ссылки ведут на одну и ту же страницу?

2018-06-18 07:45 UTC, evgenyrodionov commented on src/Main/TweetList/SitePreview.js
> +  ${'' /* border: 1px solid #e1e8ed;
мусор нужно выкидывать

2018-06-18 07:45 UTC, evgenyrodionov commented on src/index.css
> +  font-family: HelveticaNeue, Helvetica, sans-serif;
гельветика нью не так пишется

2018-06-18 08:00 UTC, tokachev commented on src/Main/TweetList/Menu.js
> +    <MenuLink to="/EveryInteract">Tweets & replies</MenuLink>
Но ведь у нас нет пока других страниц. На какие страницы тогда делать ссылки?

2018-06-18 08:02 UTC, evgenyrodionov commented on src/Main/TweetList/Menu.js
> +    <MenuLink to="/EveryInteract">Tweets & replies</MenuLink>
Подумай

2018-06-18 08:07 UTC, tokachev commented on src/Main/TweetList/Menu.js
> +    <MenuLink to="/EveryInteract">Tweets & replies</MenuLink>
Сделать ссылки на "/tweets",  "/replies" и т.д., а с них редирект на "/EveryInteract"?

2018-06-18 08:08 UTC, evgenyrodionov commented on src/Main/TweetList/Menu.js
> +    <MenuLink to="/EveryInteract">Tweets & replies</MenuLink>
Плз, включи немного голову

2018-06-19 11:11 UTC, imevro approved these changes

2018-06-19 11:11 UTC, evgenyrodionov commented on src/App.js
> +      <meta charSet="utf-8" />
а зачем?

2018-06-19 11:15 UTC, tokachev commented on src/App.js
> +      <meta charSet="utf-8" />
Да, не за чем. В примере увидел и перенес. Удалить, запушить, заново отправить запрос на ревью?

2018-06-20 20:43 UTC, imevro requested changes

2018-06-20 20:43 UTC, evgenyrodionov commented on src/Main/OfferSidebar/Trend.js
> +    <Name to={"/search?=" + props.name}>{props.name}</Name>
используй es template strings

2018-06-22 20:59 UTC, imevro requested changes

2018-06-22 20:59 UTC, evgenyrodionov commented on src/Main/CommonFollowers/index.js
> +const List = styled.div`
почему у тебя всё дивами?

2018-06-25 15:22 UTC, imevro approved these changes

2018-06-25 15:22 UTC, merged

2018-06-25 15:22 UTC, evgenyrodionov commented
Не забудь сделать гит пулл перед тем как стартовать новые ветки от мастера

Если уже делал новую ветку от этой, то коммитни изменения, сделай новую от мастера и туда черри-пиком и забери коммиты

Напиши мне в телеграм с ссылкой на этот пуллреквест, добавлю в курсач и второй этап